### ISSUE TITLE
Add filter by 'name' in '/resource-roles' endpoint

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/resources-api#25]
Related issue: https://github.com/topcoder-platform/community-app/issues/4380
Endpoint: `resource-roles`

- Currently only **isActive** is a filter options
- This endpoint will be used to get **roleId** from `Submitter` role, then will be used in Register to challenge call

**Comment by rootelement** [comment]
Fixed in https://github.com/topcoder-platform/resources-api/commit/14d2b409ce370e1ce5cff9c47a494d7007cff269
