### ISSUE TITLE
`/resources?challengeId=XXX&roleId=XXX` not filtered the roleId provided

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/resources-api#28]
Endpoint: `/resources`
Params: {
  challengeId: UUID,
  roleId: UUID,
}

Issue: Passing `roleId` as params to filter, but still getting all roles in return.

Usage: Trying to get registrants from XXX challenge with `Submitter` role

**Comment by rootelement** [comment]
This is complete in the latest push, please try again.

**Comment by luizrrodrigues** [comment]
@rootelement I'm still seeing all roles returning:

![image](https://user-images.githubusercontent.com/7029641/83765483-9b857d00-a651-11ea-8b56-87d3f0b4e450.png)

**Comment by rootelement** [comment]
Interesting. CircleCI Deploy failed. Fixed. Deploying now. Will confirm in about 10 min

**Comment by rootelement** [comment]
This is confirmed working on dev now.
<img width="969" alt="Screen Shot 2020-06-04 at 10 18 42 AM" src="https://user-images.githubusercontent.com/5400156/83768449-ccaf7e80-a64c-11ea-845e-2130cc668110.png">

**Comment by luizrrodrigues** [comment]
Cool, looks good now.
