### ISSUE TITLE
`/resources?challengeId=XXX&roleId=XXX` requesting m2m token

### ISSUE THREAD

**Issue by luizrrodrigues** [topcoder-platform/resources-api#31]
Endpoint: `/resources?challengeId=XXX&roleId=XXX`

Description: This request is needed to get **registrants** from challenge, currently only m2m is allowed: 
`Only M2M, admin or user with full access role can perform this action`

1. Need to be allowed to use the user token.
2. I think we need to be allowed to request without token too because we need to show this if use not logged too or we going to hide the Registrants if user not logged?

![image](https://user-images.githubusercontent.com/7029641/84584313-1892be00-add9-11ea-84ca-85a416ec650c.png)

**Comment by luizrrodrigues** [comment]
cc @sushilshinde

**Comment by sushilshinde** [comment]
This comment https://github.com/topcoder-platform/submissions-api/issues/181#issuecomment-643736342

Also applies here as well.

**Comment by rootelement** [comment]
This should be fixed on Resources api @luizrrodrigues . You should be able to get the resources either passing m2m, user jwt, or no jwt.

https://api.topcoder-dev.com/v5/resources?challengeId=1958ee63-61b7-439e-8527-d9b502366eb2

If no jwt is passed, only resources of type Submitter are returned.

**Comment by luizrrodrigues** [comment]
Thanks @rootelement

**Comment by rootelement** [comment]
@luizrrodrigues if this is fixed, please close it

**Comment by luizrrodrigues** [comment]
@rootelement Sorry, I forget to close this one.

Was fixed. Thanks!
