### ISSUE TITLE
Pagination Issue

### ISSUE THREAD

**Issue by rootelement** [topcoder-platform/resources-api#43]
If there are a bunch of resources on a challenge, this line is going to be an issue:
https://github.com/topcoder-platform/resources-api/blob/e4ad10a8236c04da1210a77a5d225624ba5b4deb/src/services/ResourceService.js#L244

**Comment by ThomasKranitsas** [comment]
Fixed in https://github.com/topcoder-platform/resources-api/commit/3da27569ee88357beaefd7e1683fb60e8c51a24e

**Comment by rootelement** [comment]
Fixed and paid
