### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by ThomasKranitsas** [topcoder-platform/resources-api#56]
The `GET /resources` endpoint is no longer working correctly. Even though there are records for a member/challenge combination, the API does not return anything.

### AWS: 
<img width="1177" alt="Screenshot 2021-01-02 at 1 37 57 PM" src="https://user-images.githubusercontent.com/4612921/103456737-9b418300-4d01-11eb-80a8-fc8b80f0f6da.png">

### API response:
<img width="1382" alt="Screenshot 2021-01-02 at 1 49 21 PM" src="https://user-images.githubusercontent.com/4612921/103456739-a1376400-4d01-11eb-9222-5d87d0930613.png">

**Comment by maxceem** [comment]
@ThomasKranitsas I also can confirm this. For some old challenges, I get resources. But all new challenges, if I create resources they are not returned. But if I try to create a resource again, I get an error that such a resource already exists.

**Comment by ThomasKranitsas** [comment]
Commits
- https://github.com/topcoder-platform/resources-api/commit/0537463407c34439d7b3b32cf20498df6d4fa6d1
- https://github.com/topcoder-platform/resources-api/commit/b3e4207475dd72ea0266c1543fd14eacc5520022

cc @rootelement

**Comment by ThomasKranitsas** [comment]
@maxceem it's been fixed and deployed on dev

**Comment by maxceem** [comment]
Thanks, @ThomasKranitsas. As per quick testing works good.

**Comment by vikasrohit** [comment]
is it moved to prod @ThomasKranitsas @rootelement ?

**Comment by acshields** [comment]
@ThomasKranitsas @rootelement - this issue is blocking a client from launching a challenge. Has this been deployed to prod?
