### ISSUE TITLE
Role check

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/resources-api#8]
The resource API isn't doing a full role check, especially in dev.  We need to audit the roles it's looking for to make sure they properly match what's happening in both dev and prod.  Just using two roles probably isn't the best approach.

There are numerous odd roles defined in the Topcoder platform, so we need to ensure that the role check matches with what's expected in both dev and prod.

**Comment by rootelement** [comment]
@jmgasper this is an old issue. Is this still a concern?

**Comment by rootelement** [comment]
@ThomasKranitsas please check this

**Comment by rootelement** [comment]
Tested and working in current
